config/routes.rb
Rails.application.routes.draw do
  get 'posts/search', to: 'posts#search'
  resources :posts do
    resources :comments
	end
  
  resources :users, except: [:index, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  get '/home', to: 'sessions#home'
  get '/login', to: 'sessions#new'


end

app/models/categories_post.rb
class CategoriesPost < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categories_posts
  has_many :posts, through: :categories_posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commenter, foreign_key: :user_id, class_name: User
  belongs_to :post

  validates :message, :post, :commenter, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, foreign_key: :user_id, class_name: User

  has_many :categories_posts
  has_many :categories, through: :categories_posts

  has_many :comments

  validates :title, :content, presence: true


  def self.search(string)
  	
  	Post.where("content LIKE ? OR title LIKE ? ", "%#{string}%", "%#{string}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :posts

  attr_accessor :password, :password_confirmation

  validates :name, :email, presence: true
  validates :password, confirmation: true
  validates_with Validators::NameValidator
  # validate :full_name 
  #User.includes(:posts)
  

  # def full_name
  #   errors.add(:name, "Enter firstname and surname") unless name.split(' ').size =="2"
  # end 
  
  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user.encrypted_password == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    end
  end

  def self.search_posts(name)
    #binding.pry
    user = User.where('name LIKE ?', "%#{name}").first
    User.where('name LIKE ?', "%#{name}").first
   
    
    user.posts
  end

  def register
    if valid?
      self.password_salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, password_salt)
    end

    save
  end
end

app/models/validators/name_validator.rb
module Validators
	class Validators::NameValidator < ActiveModel::Validator

    def validate(instance)
    	
      instance.errors.add(:name, "Enter firstname and surname") unless instance.name.split(' ').size ==2
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.where(id: session[:user_id]).first
  end

  def authenticate_user!
    redirect_to login_path unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    comment = @post.comments.new(permitted_comments_attributes)

    comment.commenter = current_user

    unless comment.save
      flash[:errors] = comment.errors.full_messages
    end

    redirect_to @post
  end

  def permitted_comments_attributes
    params.require(:comment).permit(:message)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new]
  before_filter :find_post, only: [:show, :edit, :update]
  before_filter :authorized_user!, only: [:edit, :update]
  before_filter :authorized_search, only: [:search]
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(permitted_post_params)
    @post.category_ids = Category.where(name: params[:post][:category_ids]).pluck(:id)

    if @post.save
      redirect_to @post
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    
  end

  def index

    @posts=Post.includes(:author)
  end

  def edit
  end

  def update
    @post.category_ids = Category.where(name: params[:post][:category_ids]).pluck(:id)

    if @post.update_attributes(permitted_post_params)
      redirect_to @post
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end
  def search
    
    search = params[:q]
    
    @posts = Post.search(search) + User.search_posts(search)
   # @posts = Post.includes(:author).search(search)
  end


  private

  def permitted_post_params
    params.require(:post).permit(:title, :content)
  end
  def authorized_search
      redirect_to posts_path unless params[:q]
   end

  def find_post
    
    @post = Post.find(params[:id])
  end

  def authorized_user!
    redirect_to @post unless @post.author == current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authenticate_user!, only: [:home, :destroy]

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user
      session[:user_id] = user.id
      redirect_to home_path
    else
      render :new
    end
  end

  def home
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(permitted_user_attrs)

    if @user.register
      redirect_to login_path
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def show
  end

  private

  def permitted_user_attrs
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def categories
    Hash[Category.all.map { |c| [c.id, c.name] }]
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new_comment.html.erb
<div>
  <div>You can comment in the below box: </div>
  <%= form_for comment, url: post_comments_path(comment.post, comment) do |f| %>
    <%= f.text_field :message %>
    <%= f.submit 'Comment' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div>
  <% if flash[:errors] %>
    <% flash[:errors].each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <%= form_for post do |f| %>
    <label for="title">
      Title: <%= f.text_field :title %>
    </label>

    <br />

    <% categories.each do |id, category| %>
      <%= check_box_tag 'post[category_ids][]', category %> <%= category %>
    <% end %>

    <br />
    
    Content: <br/>
    <%= f.text_area :content, rows: 25, cols: 100 %>

    <br />

    <%= f.submit %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h2>Posts list</h2>
<%= link_to 'Home', home_path %>
<%= form_tag(posts_search_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q, nil, {required: true})%>
  <%= submit_tag("Search") %>
<% end %>

<% @posts.each do |post| %>
	<h2><%= link_to post.title, post_path(post) %></h2> by <%= post.author.name %>
	<div><%= post.content %></div>
<% end %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/search.html.erb
<h1>Listing posts</h1>
<%@posts.each do|post|%>
	<h3>
	<%= link_to post.title, post_path(post) %></h3>
	<p><%= post.try(:content) %></p>

	<br>
<% end %>


<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |message| %>
    <div><%= message %></div>
  <% end %>
<% end %>

<h1><%= @post.title %></h1> by <%= @post.author.name %>
<div><%= @post.content %></div>
<% if @post.categories.present? %>
  <div>This post is tagged with <%= @post.categories.map(&:name).join(', ') %></div>
<% end %>

<div class="comments">
  Comments for this post:

  <% @post.comments.each do |comment| %>
    <div>
      <%= comment.message %> by <%= comment.commenter.name %>
    </div>
  <% end %>

  <br/><br/>
  <%= render 'comments/new_comment', comment: @post.comments.new %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Signup</h1>
<% if flash[:errors] %>
  <% flash[:errors].each do |message| %>
    <div><%= message %></div>
  <% end %>
<% end %>

<%= form_for @user do |f| %>
  <label>
    Name: <%= f.text_field :name %>
  </label>
  <label>
    Email: <%= f.email_field :email %>
  </label>
  <label>
    Password: <%= f.password_field :password %>
  </label>
  <label>
    Confirm Password: <%= f.password_field :password_confirmation %>
  </label>
  <%= f.submit 'Sign Up' %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>